EvaluationsBundle\Entity\Test:
    type: entity
    table: test
    id:
        idTest:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_test
            generator:
                strategy: SEQUENCE
    fields:
        matter:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        institution:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        score:
            type: integer
            nullable: true
            options:
                unsigned: false
        percentage:
            type: integer
            nullable: true
            options:
                unsigned: false
        starttime:
            type: datetime
            nullable: true
        endtime:
            type: datetime
            nullable: true
        startenrollment:
            type: datetime
            nullable: true
        endenrollment:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
