evaluations_test:
        resource: "@EvaluationsBundle/Resources/config/routing/test.php"
        prefix:   /test

evaluations_question:
        resource: "@EvaluationsBundle/Resources/config/routing/question.php"
        prefix:   /question

evaluations_testquestion:
    resource: "@EvaluationsBundle/Resources/config/routing/testquestion.php"
    prefix:   /testquestion

evaluations_area:
    resource: "@EvaluationsBundle/Resources/config/routing/area.php"
    prefix:   /area

evaluations_usersystem:
        resource: "@EvaluationsBundle/Resources/config/routing/usersystem.php"
        prefix:   /usersystem

login_homepage:
    path:     /login
    defaults: { _controller: EvaluationsBundle:Login:login }

logout_homepage:
    path:     /logout
    defaults: { _controller: EvaluationsBundle:Login:logout }

validate_homepage:
    path:     /validate
    defaults: { _controller: EvaluationsBundle:Login:validate }

evaluations_homepage:
    path:     /home
    defaults: { _controller: EvaluationsBundle:Default:index }

#indexerror_homepage:
#    path:     /Test
#    defaults: { _controller: EvaluationsBundle:Test:indexError }
