evaluations_test:
        resource: "@EvaluationsBundle/Resources/config/routing/test.php"
        prefix:   /test

evaluations_testquestion:
    resource: "@EvaluationsBundle/Resources/config/routing/testquestion.php"
    prefix:   /testquestion

evaluations_homepage:
    path:     /
    defaults: { _controller: EvaluationsBundle:Default:index }

