evaluations_test:
        resource: "@EvaluationsBundle/Resources/config/routing/test.php"
        prefix:   /test


evaluations_question:
        resource: "@EvaluationsBundle/Resources/config/routing/question.php"
        prefix:   /question

evaluations_testquestion:
    resource: "@EvaluationsBundle/Resources/config/routing/testquestion.php"
    prefix:   /testquestion

evaluations_area:
    resource: "@EvaluationsBundle/Resources/config/routing/area.php"
    prefix:   /area

evaluations_usersystem:
        resource: "@EvaluationsBundle/Resources/config/routing/usersystem.php"
        prefix:   /usersystem

evaluations_homepage:
    path:     /
    defaults: { _controller: EvaluationsBundle:Default:index }
