evaluations_test:
        resource: "@EvaluationsBundle/Resources/config/routing/test.php"
        prefix:   /test

evaluations_testquestion:
    resource: "@EvaluationsBundle/Resources/config/routing/testquestion.php"
    prefix:   /testquestion

evaluations_area:
    resource: "@EvaluationsBundle/Resources/config/routing/area.php"
    prefix:   /area

#evaluations_questionselector:
#    path:     /
#    defaults: { _controller: EvaluationsBundle:questionSelector:index }

evaluations_homepage:
    path:     /
    defaults: { _controller: EvaluationsBundle:Default:index }

